language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer require symfony/http-foundation:${SYMFONY_VERSION}
  - composer install --prefer-source --dev
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpunit --coverage-text
  - phpcs --standard=psr2 ./lib

env:
  - SYMFONY_VERSION="~2.0"
  - SYMFONY_VERSION="2.0.*"
  - SYMFONY_VERSION="2.1.*"
  - SYMFONY_VERSION="2.2.*"
  - SYMFONY_VERSION="2.3.*"
